[Time]
NTP=pool.ntp.org time.google.com time.windows.com
FallbackNTP=0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org time1.google.com time2.google.com time3.google.com time4.google.com
RootDistanceMaxSec=5
PollIntervalMinSec=32
PollIntervalMaxSec=2048
ConnectionRetrySec=30
SaveIntervalSec=60
